network_passphrase = "Test SDF Network ; September 2015"
default_network = "testnet"

[network.testnet]
rpc_url = "https://soroban-testnet.stellar.org:443"
network_passphrase = "Test SDF Network ; September 2015"

[network.mainnet]
rpc_url = "https://soroban-rpc.mainnet.stellar.org:443"
network_passphrase = "Public Global Stellar Network ; September 2015"


